version: '3.8'
services:
  std:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - 8080:8080
    env_file:
      - demo.env
    volumes:
      - .:/etc/contrast:ro
    networks:
      - extbridge
  gin:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.agent
      args:
        FRAMEWORK: gin
    ports:
      - 8080:8080
    env_file:
      - demo.env
    volumes:
      - .:/etc/contrast:ro
    networks:
      - extbridge
  julienschmidt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.agent
      args:
        FRAMEWORK: julienschmidt
    ports:
      - 8080:8080
    env_file:
      - demo.env
    volumes:
      - .:/etc/contrast:ro
    networks:
      - extbridge
networks:
  extbridge:
    driver: bridge
